# Generated by Django 3.2.16 on 2022-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
